export const AJOUTER_VIN = 'AJOUTER_VIN'
export const INIT_LISTE = 'INIT_LISTE'
export const SUPPRIMER_VIN = 'SUPPRIMER_VIN'
export const UPDATE_VIN = 'UPDATE_VIN'

export const TOOGLE_FILTREALL = 'TOOGLE_FILTREALL'

export const AJOUTER_EMPLACEMENT = 'AJOUTER_EMPLACEMENT'
export const SUPPRIMER_EMPLACEMENT = 'SUPPRIMER_EMPLACEMENT'
